#!/usr/bin/perl -w

use strict;
use warnings;
use Geo::IP;
use constant SAMPLE => 512;
use constant IMIX => 500;
use constant OUT_DIR => ($ARGV[1] ? $ARGV[1] : '/sflow/aggregated');

my %TIMECNTRS = ();
my %PEERS = ();
my %PORTS = ();
my %UTILIZATION = ();
my %PORTCOUNTERS = ();
my %COUNTRIES = ();
my %COUNTRIES_STATS = ();
my %CITIES = ();
my %IPCOUNTRIES = ();

my $countrybase = Geo::IP->open("/opt/etc/GeoIP.dat",GEOIP_MEMORY_CACHE) or die "Failed to open Country GeoIP database!";
my $citybase = Geo::IP->open("/opt/etc/GeoLiteCity.dat",GEOIP_MEMORY_CACHE) or die "Failed to open City GeoIP database!";

my $file = $ARGV[0];
my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);

mkdir OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min;
mkdir OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . '/ports';
mkdir OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . '/countries';

open C, "/opt/etc/networks.conf" or die "Failed to open network configuration file! $!";
my @CFGNETS = <C>;
foreach (@CFGNETS) {
	chomp $_;
}
close C;


open P, "/opt/etc/ports.conf" or die "Failed to open network ports configuration file! $!";
my @CFGPORTS = <P>;
foreach (@CFGPORTS) {
	chomp $_;
	$PORTCOUNTERS{$_} = {};
}
close P;
my $PORTS = '@' . join ('@',@CFGPORTS) . '@';


open F, $file or die "Failed to opent $file for processing. $!\n";


while(<F>) {
	chomp;
	my @line = split /,/;
	#print $line[10],$line[11],"\n";
	my $minute = int($line[0] / 60);
	my ($fromip,$toip) = ($line[10],$line[11]);
	my $ssize = $line[20];
	
	my $cfrom = $countrybase -> country_code_by_addr($fromip) || 'NA';
	my $cto = $countrybase -> country_code_by_addr($toip) || 'NA';

	if(!exists $IPCOUNTRIES{$fromip}) {
		$IPCOUNTRIES{$fromip} = {}
	}

	if(!exists $IPCOUNTRIES{$toip}) {
		$IPCOUNTRIES{$toip} = {}
	}

	if(!exists $IPCOUNTRIES{$fromip}{$cto}) {
		$IPCOUNTRIES{$fromip}{$cto} = [1,1];
	}


	if(!exists $IPCOUNTRIES{$toip}{$cfrom}) {
		$IPCOUNTRIES{$toip}{$cfrom} = [1,1];
	}

	$IPCOUNTRIES{$toip}{$cfrom}->[1] += $ssize; 
	$IPCOUNTRIES{$fromip}{$cto}->[0] += $ssize; 

	if(!exists $COUNTRIES{$cfrom}) {
		$COUNTRIES{$cfrom} = {};
		$COUNTRIES_STATS{$cfrom} = [1,1];
	}

	if(!exists $COUNTRIES{$cto}) {
		$COUNTRIES{$cto} = {};
		$COUNTRIES_STATS{$cto} = [1,1];
	}
		
	if(!exists $COUNTRIES{$cfrom}{$fromip}) {
		$COUNTRIES{$cfrom}{$fromip} = [1,1];
	}

	if(!exists $COUNTRIES{$cto}{$toip}) {
		$COUNTRIES{$cto}{$toip} = [1,1];
	}

	$COUNTRIES_STATS{$cfrom}->[0] += $ssize;
	$COUNTRIES_STATS{$cto}->[1]   += $ssize;

	$COUNTRIES{$cfrom}{$fromip}->[0] += $ssize;
	$COUNTRIES{$cto}{$toip}->[1]     += $ssize;


	if(!exists $UTILIZATION{$fromip}) {
		$UTILIZATION{$fromip} = [1,1];			
	}
	if(!exists $UTILIZATION{$toip}) {
		$UTILIZATION{$toip} = [1,1];			
	}

	$UTILIZATION{$fromip}->[0]+=$ssize;
	$UTILIZATION{$toip}->[1]+=$ssize;
	
	my ($fromport,$toport) = ('@' . $line[15] . '@' , '@' . $line[16] . '@');
	if (1) { #foreach my $net (@CFGNETS) {
		if(1) {                      # $line[10] =~ /$net/)
 			$fromip = $line[10];
			if(!exists $TIMECNTRS{$fromip}) {
				$TIMECNTRS{$fromip} = {};			
			}
			if(!exists $PEERS{$fromip}) {
				$PEERS{$fromip} = {};			
			}

			if(!exists $PEERS{$fromip}) {
				$PEERS{$fromip} = {};			
			}


			if(!exists $PORTS{$fromip}) {
				$PORTS{$fromip} = {};			
			}
			
			if($PORTS =~ /$toport/ && !exists $PORTS{$fromip}{$line[16]}) {
				$PORTS{$fromip}{$line[16]} = [1,1,1,1];
				# 
				if(!exists $PORTCOUNTERS{$line[16]}{$fromip}) {
					$PORTCOUNTERS{$line[16]}{$fromip} = [1,1];			
				}
			}

			if($PORTS =~ /$fromport/ && !exists $PORTS{$fromip}{$line[15]}) {
				$PORTS{$fromip}{$line[15]} = [1,1,1,1];
				# 
				if(!exists $PORTCOUNTERS{$line[15]}{$fromip}) {
					$PORTCOUNTERS{$line[15]}{$fromip} = [1,1];
				}

			}

			if($PORTS =~ /$fromport/) {
    				$PORTS{$fromip}{$line[15]} -> [0] +=$ssize;
				$PORTCOUNTERS{$line[15]}{$fromip}->[0]+=$ssize;
			}

			if($PORTS =~ /$toport/) {
    				$PORTS{$fromip}{$line[16]} -> [1] +=$ssize;
				$PORTCOUNTERS{$line[16]}{$fromip}->[1]+=$ssize;
			}

			if(!exists $TIMECNTRS{$fromip}{$minute}) {
				$TIMECNTRS{$fromip}{$minute} = [1,1];
			}

			if(!exists $PEERS{$fromip}{$line[11]}) {
				$PEERS{$fromip}{$line[11]} = [1,1,$cto];			
			}

			$TIMECNTRS{$fromip}{$minute} -> [0] +=$ssize;
			$PEERS{$fromip}{$line[11]} -> [0] +=$ssize;
		}

		if(1) { #$line[11] =~ /$net/) {
			$toip = $line[11];
			if(!exists $TIMECNTRS{$toip}) {
				$TIMECNTRS{$toip} = {};
			}
			
			if(!exists $PEERS{$toip}) {
				$PEERS{$toip} = {};			
			}

			if(!exists $PORTS{$toip}) {
				$PORTS{$toip} = {};			
			}

			if($PORTS =~ /$toport/ && !exists $PORTS{$toip}{$line[16]}) {
				$PORTS{$toip}{$line[16]} = [1,1,1,1];
				# 
				if(!exists $PORTCOUNTERS{$line[16]}{$toip}) {
					$PORTCOUNTERS{$line[16]}{$toip} = [1,1];			
				}

			}

			if($PORTS =~ /$fromport/ && !exists $PORTS{$toip}{$line[15]}) {
				$PORTS{$toip}{$line[15]} = [1,1,1,1];
				# 
				if(!exists $PORTCOUNTERS{$line[15]}{$toip}) {
					$PORTCOUNTERS{$line[15]}{$toip} = [1,1];
				}
			}

			if($PORTS =~ /$fromport/) {
    				$PORTS{$toip}{$line[15]} -> [2] +=$ssize;
				$PORTCOUNTERS{$line[15]}{$toip}->[1]+=$ssize;

			}

			if($PORTS =~ /$toport/) {
    				$PORTS{$toip}{$line[16]} -> [3] +=$ssize;
				$PORTCOUNTERS{$line[16]}{$toip}->[0]+=$ssize;
			}

			if(!exists $TIMECNTRS{$toip}{$minute}) {
				$TIMECNTRS{$toip}{$minute} = [1,1];
			}
			if(!exists $PEERS{$toip}{$line[10]}) {
				$PEERS{$toip}{$line[10]} = [1,1,$cfrom];			
			}

			$TIMECNTRS{$toip}{$minute} -> [1] +=$ssize;
			$PEERS{$toip}{$line[10]} -> [1] +=$ssize;

		}
	}
}

close F;

foreach my $ip (keys %TIMECNTRS) {
	
	my @parts = split /\./, $ip;
	mkdir OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . "/" . $parts[0];
	
	open W,">", OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . "/" . $parts[0] . "/$ip.packets" or die "Failed to open stat file for ip $ip. $!";
	foreach my $m (sort keys %{$TIMECNTRS{$ip}}) {
		print W "$m\t", $TIMECNTRS{$ip}{$m}->[0],"\t",$TIMECNTRS{$ip}{$m}->[1],"\n";
	}
	close W;
}

foreach my $ip (keys %PEERS) {
	
	my @parts = split /\./, $ip;
	mkdir OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . "/" . $parts[0];
	
	open W,">", OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . "/" . $parts[0] . "/$ip.peers" or die "Failed to open stat file for ip $ip. $!";
	foreach my $peer (sort keys %{$PEERS{$ip}}) {
		print W "$peer\t", $PEERS{$ip}{$peer}->[0],"\t",$PEERS{$ip}{$peer}->[1],"\t",$PEERS{$ip}{$peer}->[2],"\n";
	}
	close W;
}


foreach my $ip (keys %IPCOUNTRIES) {
	
	my @parts = split /\./, $ip;
	mkdir OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . "/" . $parts[0];
	
	open W,">", OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . "/" . $parts[0] . "/$ip.geo" or die "Failed to open stat file for ip $ip. $!";
	foreach my $country (sort keys %{$IPCOUNTRIES{$ip}}) {
		print W "$country\t", $IPCOUNTRIES{$ip}{$country}->[0], "\t", $IPCOUNTRIES{$ip}{$country}->[1], "\n";
	}
	close W;
}


foreach my $ip (keys %PORTS) {
	
	my @parts = split /\./, $ip;
	mkdir OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . "/" . $parts[0];
	
	open W,">", OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . "/" . $parts[0] . "/$ip.ports" or die "Failed to open stat file for ip $ip. $!";
	foreach my $p (sort keys %{$PORTS{$ip}}) {
		print W "$p\t", $PORTS{$ip}{$p}->[0],"\t",$PORTS{$ip}{$p}->[1], "\t", $PORTS{$ip}{$p}->[2],"\t",$PORTS{$ip}{$p}->[3],"\n";
	}
	close W;
}

foreach my $port (keys %PORTCOUNTERS) {
	open W,">", OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . "/ports/$port.ips" or die "Failed to open stat file for ports $port. $!";
	foreach my $ip (sort keys %{$PORTCOUNTERS{$port}}) {
		print W "$ip\t", $PORTCOUNTERS{$port}{$ip}->[0], "\t", $PORTCOUNTERS{$port}{$ip}->[1],"\n";
	}
	close W;
}

open W,">", OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . "/_utilization" or die "Failed to open utilization. $!";
foreach my $ip (sort keys %UTILIZATION) {
	print W "$ip\t", $UTILIZATION{$ip}->[0],"\t", $UTILIZATION{$ip}->[1], "\n";
}

foreach my $country (keys %COUNTRIES) {
	next if !$country;
	open W,">", OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . "/countries/$country.ips" or die "Failed to open stat file for country $country. $!";
	foreach my $ip (sort keys %{$COUNTRIES{$country}}) {
		next if !$ip;
		print W "$ip\t", $COUNTRIES{$country}{$ip}->[0], "\t", $COUNTRIES{$country}{$ip}->[1],"\n";
	}
	close W;
}

open W,">", OUT_DIR . '-' . $mday . '-' . $hour . '-' . $min . "/countries/_stats" or die "Failed to open country statistics. $!";
foreach my $c (sort keys %COUNTRIES_STATS) {
	print W "$c\t", $COUNTRIES_STATS{$c}->[0],"\t", $COUNTRIES_STATS{$c}->[1], "\n";
}

